services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BACKEND_TARGET:-backend-dev-stage}
    develop:
      watch:
        - action: rebuild
          path: ./backend
          ignore:
            - ./backend/obj/
            - ./backend/bin/
        - action: rebuild
          path: ./scripts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=task4;User=app;Password=app;
      - App__PublicUrl=https://abzabza.ru

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${FRONTEND_TARGET:-frontend-dev-stage}
    develop:
      watch:
        - path: ./frontend
          target: /app
          action: sync
          ignore:
            - ./frontend/node_modules/
            - ./frontend/dist/
            - ./frontend/.quasar/
        - path: ./frontend/package.json
          target: /app/package.json
          action: sync+restart
        - path: ./frontend/quasar.config.ts
          target: /app/quasar.config.ts
          action: sync+restart
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HMR_CLIENT_PORT=8000
      - API_PROXY_TARGET=http://backend:8080
    ports:
      - "8000:80"
    depends_on:
      - backend

volumes:
  frontend_node_modules:
