services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BACKEND_TARGET:-backend-dev-stage}
    develop:
      watch:
        - action: rebuild
          path: ./backend
          ignore:
            - ./backend/obj/
            - ./backend/bin/
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=task4;User=app;Password=app;
      - App__PublicUrl=https://abzabza.ru

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${FRONTEND_TARGET:-frontend-production-stage}
    develop:
      watch:
        - path: ./frontend/src
          target: /app/src
          action: sync
        - path: ./frontend/package.json
          target: /app/package.json
          action: restart
        - path: ./frontend/quasar.config.ts
          target: /app/quasar.config.ts
          action: restart
    ports:
      - "8000:80"
    depends_on:
      - backend

volumes:
  frontend_node_modules:
